title: The VoxTube Dataset
description: VoxTube is a multilingual speaker recognition dataset released by ID R&D Inc.
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
